### ISSUE TITLE
Please add copyright license header to all source files

### ISSUE THREAD

**Issue by petterreinholdtsen** [sr99622/libonvif#10]
I notice some files have information about GPL v2+ in their headers, while others do not.  Please add it to all file headers.  It would make it easier for those packaging the library for Linux distributions to automatically track copyright status of the project.

**Comment by petterreinholdtsen** [comment]
The following files could use more details on their copyright status, including right holder, copyright year and license.  And in case of public domain works, author and year written and where the file came from.

```
CMakeLists.txt
example/CMakeLists.txt
example/onvif-discover.c
example/onvif-getall.c
include/cencode.h
include/sha1.h
recipe/bld.bat
recipe/build.sh
recipe/meta.yaml
sample/CMakeLists.txt
sample/configtab.cpp
sample/configtab.h
sample/main.cpp
sample/mainwindow.cpp
sample/mainwindow.h
sample/sample.pro
src/cencode.c
src/sha1.c
```

**Comment by petterreinholdtsen** [comment]
The situation is alot better now.  The only files without clear copyright license information now are these:

```
include/sha1.h
include/cencode.h
sample/sample.pro
src/cencode.c
src/sha1.c
README.md
```

**Comment by petterreinholdtsen** [comment]
The state of affairs look good now.  But why did you add the lgpl-2.0.txt file, when the source is using gpl, not lgpl?

**Comment by sr99622** [comment]
Thank you so much for your efforts helping with these issues, your work has
been invaluable.

I'm hoping to get things wrapped up very soon.  I'm currently going through
the other command line tools with the goal of merging everything into
onif-util.  I think a single command line tool with comprehensive
functionality would make the most sense.  The time routines will take a
little testing to get right, but it shouldn't take too long.  The man page
will be updated and will include the copyright info you added.  Then we
could tag a new Release.

I did want to ask about the debian package.  Would that include the gui
utility as well?

**Comment by petterreinholdtsen** [comment]
[sr99622]
> I did want to ask about the debian package.  Would that include the gui
> utility as well?

It would be up to the maintainer, ie you.  My offer it to sponsor the
package into Debian, ie review and help you upload it, not to maintain
it.  I already maintain way too many packages in Debian.  I would
recommend including it, and my draft build rules include it.  Ping me on
IRC (ref my sponsoring references) once you are ready to move forward
with getting it into Debian.

Would be nice if the GUI tool had a simple man page too. :)
-- 
Happy hacking
Petter Reinholdtsen
