### ISSUE TITLE
Strange setting of camera name

### ISSUE THREAD

**Issue by petterreinholdtsen** [sr99622/libonvif#13]
When using the Qt sample client to set the camera name of several ONVIF cameras, the final name end up being the union of the original and new new name.  One of the cameras initially had the name 'HeroSpeed IPCamera', and I set the new name to
'KameraUte', but after applying the change and closing the client and starting it again, I am told the name is something like 'KameraUte IPCamera'.  Look like some string termination is not working as it should.

**Comment by sr99622** [comment]
Indeed, this is a string termination issue and has been fixed.  Thank you so much for your help, somehow this was missed earlier.
