### ISSUE TITLE
Package libonvif in Debian?

### ISSUE THREAD

**Issue by petterreinholdtsen** [sr99622/libonvif#15]
Are you interested in getting the libonvif package into Debian?  I would be willing and able to help if you are interested in maintaining it in Debian.  I've already told Debian about this package in https://bugs.debian.org/1021980 and asked if anyone want to maintain it.  It can be a starting point.

**Comment by iam-TJ** [comment]
I've begun locally to create the Debianised package. Once it's done I can create a pull request so it is native to the project, if desired.

**Comment by petterreinholdtsen** [comment]
[TJ]
> I've begun locally to create the Debianised package. Once it's done I
> can create a pull request so it is native to the project, if desired.

I already got almost complete Debian build rules in my debian branch, so
there is probably no need for you to do this.

Are you willing to maintain the package in Debian?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
My branches to set up Debian package build rules would become easier if you tagged a new release with the latest fixes.  Time to make a new release?

**Comment by sr99622** [comment]
I have tagged a new release version 1.3.0

**Comment by petterreinholdtsen** [comment]
[sr99622]
> I have tagged a new release version 1.3.0

Very good.  I've updated my debian branch to use it. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by sr99622** [comment]
I have been experimenting with debuild and I have been able to create a working .deb installation file.  Something I noticed along the way is that I need to remove the 'if (BUILD_GUI)" condition from the CMakeLIsts.txt in order to get the onvif-camadmin binary.  This is my first experience with debian packaging, so there may be a more elegant way to achieve the effect in one of the debian files, but I just wanted to double check with you that the onvif-camadmin binary is being built in the package.

I also wanted to ask if there is a way to add ffmpeg as a dependency so that the GUI would know that the ffplay program was always there, or if that's not such a good idea.

**Comment by petterreinholdtsen** [comment]
[sr99622]
> I have been experimenting with debuild and I have been able to create
> a working .deb installation file.

Very good.

> Something I noticed along the way is that I need to remove the 'if
> (BUILD_GUI)" condition from the CMakeLIsts.txt in order to get the
> onvif-camadmin binary.  This is my first experience with debian
> packaging, so there may be a more elegant way to achieve the effect in
> one of the debian files, but I just wanted to double check with you
> that the onvif-camadmin binary is being built in the package.

Are you using my debian branch for this?  I solved the same issue by
adjusting debian/rules to add -DBUILD_GUI, which make me suspect you are
not looking at the branch I created.

> I also wanted to ask if there is a way to add ffmpeg as a dependency
> so that the GUI would know that the ffplay program was always there,
> or if that's not such a good idea.

Sure, just add the dependency to debian/control.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by sr99622** [comment]
I managed to find the debian branch on your fork, and see the configuration for the build.  It looks like the package is ready to go.

I have done some more testing and things are working as expected so I am comfortable uploading the package.

**Comment by petterreinholdtsen** [comment]
[sr99622]
> I managed to find the debian branch on your fork, and see the
> configuration for the build.  It looks like the package is ready to
> go.

The setup I had was not handling library symbol versioning, so I guess
that need to be added.  I am not very skilled with shared library
packaging myself, but know there are howtos on the web.  I'll track one
down and try to have it ready for when you find me on IRC.

> I have done some more testing and things are working as expected so I
> am comfortable uploading the package.

Very good to hear. :)

--
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
[sr99622]
> Closed #15 as completed.

For the record, the package is not yet in Debian.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by sr99622** [comment]
Hope you are having a nice day.

I created a branch with viewer functionality in gui_output. There are some lintian messages but they seem to be superfluous as far as I can tell.  Regarding C library installation, the versioning works properly and files are installed to correct locations, as per your Debian branch.

I would like to merge the gui_output branch to the main, but this will overwrite previous configuration.  Perhaps you could upload in current configuration now and I can upgrade later.

Best Regards,

Stephen

**Comment by petterreinholdtsen** [comment]
[sr99622]
> Hope you are having a nice day.

I do.  I saw you had poped by IRC while I was out some days ago.  Very
glad to see you managed to get connected, and look forward to seeing you
again. :)

> I created a branch with viewer functionality in gui_output. There are
> some lintian messages but they seem to be superfluous as far as I can
> tell.  Regarding C library installation, the versioning works properly
> and files are installed to correct locations, as per your Debian
> branch.

Yes.  The only thing I worry about, which is an area I am not well
trained, is the shared library symbol versioning.  I recommend reading
<URL: https://www.debian.org/doc/debian-policy/ch-sharedlibs.html > to
learn more about it.

> I would like to merge the gui_output branch to the main, but this will
> overwrite previous configuration.  Perhaps you could upload in current
> configuration now and I can upgrade later.

Not sure what you mean here.  I am sure we can figure out uploading, but
did not understand the stuff about merging branches and overwriting
configuration.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by sr99622** [comment]
I went through the debian policy on shared libs and regenerated the debian
install folder in the gui_output branch.  I have included a symbols file
based on what was outlined in the debian policy.  There are also some
.substvars files created by dh_make that have some shlib:Depends entries
that specify dependency versions.

I changed the debian version number from 0 to 1, it seems like dh_make
wanted to use that number based on major revision number

When I update the gui_output branch on git hub, the run checker fails, so I
don't want to merge the branch in case the changes break something already
exisiting.

Due to time zone difference, I wlll try contacting you again on IRC in my
morning hours tomorrow

**Comment by petterreinholdtsen** [comment]
You might find the planned freeze dates on https://release.debian.org/ useful for your planning.  Note, with a working debian/tests/ setup the propagation time from upload to reacing testing can be redused from 5 to 2 days.

**Comment by sr99622** [comment]
Thank you so much for the updates.  Things are going well with the QtAV replacement.  I have overcome the biggest hurdles, need to clean up quite a bit however, will keep you updated over the next few days.

**Comment by petterreinholdtsen** [comment]
Hi. Any news on the QtAV replacement?

**Comment by sr99622** [comment]
Hope you had a great weekend,

I was able to get it working on the libavio branch.  There are dependencies
on ffmpeg and sdl2, which you can install with

sudo apt install libavcodec-dev
sudo apt install libavdevice-dev
sudo apt install libsdl2-dev

I made a few other changes, notably, the name change of the gui program to
onvif-gui and a bunch of housekeeping.

**Comment by petterreinholdtsen** [comment]
[sr99622]
> I made a few other changes, notably, the name change of the gui program to
> onvif-gui and a bunch of housekeeping.

Very good.  I'll test it the next few days when I get near a ONVIF
camera again.

I was able to build the branch on Debian 11 using 'debuild' and the
following patch to document the build dependencies and adding a required
pthread link dependency.

diff --git a/debian/control b/debian/control
index 8a8ef25..a7be7eb 100644
--- a/debian/control
+++ b/debian/control
@@ -4,6 +4,9 @@ Maintainer: Stephen Rhodes ***@***.***>
 Build-Depends: debhelper-compat (= 13)
  , cmake
  , libxml2-dev
+ , libavcodec-dev
+ , libavdevice-dev
+ , libsdl2-dev
 Standards-Version: 4.6.0
 Section: libs
 Homepage: https://github.com/sr99622/libonvif/
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 728402f..6187e69 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -158,6 +158,7 @@ if (BUILD_GUI)
         ${LIBXML2_LIBRARIES}
         ${FFMPEG_LIBRARIES}
         SDL2::SDL2
+        pthread
     )
 
     target_include_directories(onvif-gui PUBLIC

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
The package entered Debian today.
