### ISSUE TITLE
Install onvif-time and onvif-util only on Linux?

### ISSUE THREAD

**Issue by petterreinholdtsen** [sr99622/libonvif#18]
In de2471eedf79c7675ce4c782032193f271252f06 the tools onvif-time and onvif-util were removed after being added due to issue #3 and pull request #6 because they are claimed to be not compatible with Windows.  What about keeping them but only building and installing them on Linux, until they can be ported to Windows?  Why are they not compatible with Windows?

**Comment by petterreinholdtsen** [comment]
I pulled out the removed tools and placed them in https://github.com/petterreinholdtsen/libonvif/tree/issue-3-time-util .

**Comment by petterreinholdtsen** [comment]
https://stackoverflow.com/questions/10404448/getopt-h-compiling-linux-c-code-in-windows got some suggestions for using getopt on Windows.

**Comment by petterreinholdtsen** [comment]
It is also possible to replace getopt_long() with something else, for example https://www.boost.org/doc/libs/1_80_0/doc/html/program_options.html or https://doc.qt.io/qt-6/qcommandlineparser.html , if such dependencies are OK on Windows.  Both of these are easily available on Debian.

**Comment by sr99622** [comment]
I was able to find a header only implementation of getopt that will work on windows.  It was renamed getopt-win.h and a conditional include will tell the compiler to find the platform appropriate version

**Comment by petterreinholdtsen** [comment]
This was fixed in 70c1406a6eab817c70e63eb727da68c4c790a03f.
