### ISSUE TITLE
c linkage error occures when it is included in qt/c++ project

### ISSUE THREAD

**Issue by Mahsa-Nowruzi** [sr99622/libonvif#2]
Hi. I used your project but I ran into a problem. I followed the installation steps exactly as it was described in the "README.md" file.
The "test_onvif" file runs without any problems. But when I include <libonvif/onvif.h> in Qt, It hits "template with C linkage" error.
I use Linux system, my Qt version is 5.15.3, with QMake 3.1 and my gcc version is 11.2.0.
How can I solve this problem?

**Comment by sr99622** [comment]
I was able to reproduce the problem you described.  There seems to be something going on with libxml2.  The problem can be avoided by explicitly declaring the #include "libxml2/parser.h" prior to the #include "onvif.h" header.

I have added a sample Qt application to the source code in the sample directory that shows how to do this.  You may need to adjust the sample.pro file to match your system configuration.

**Comment by Mahsa-Nowruzi** [comment]
Thank you very much. My problem is solved.
