### ISSUE TITLE
Merge all command line tools into one onvif-cli tool?

### ISSUE THREAD

**Issue by petterreinholdtsen** [sr99622/libonvif#22]
Looking at the current set of command line tools, onvif-discover, onvif-getall, onvif-time and onvif-util, and the fact that you now got support for command line options sorted out, it occured to me that it might be better from a user point of view to merge the set into one, for example named onvif-cli or similar, and write one man page for this unified tool.  It would make it more obvious for users that they should use the onvif tool to get a GUI, and the onvif-cli tool for command line tasks.  Over time it can be extended to more tasks that should be available from the command line, like the request in issue #5.

**Comment by sr99622** [comment]
This is a good idea, will get started.

**Comment by petterreinholdtsen** [comment]
[sr99622]
> This is a good idea, will get started.

Great to hear.

For users to find out how to use the new tool, it need to print usage
information and provide a manual page with instructions on how to use
it.  At the moment one need to read the source to figure out the options
available.

Instead of maintaining a manual page in ROFF format directly, it can be
an idea to check out rst2man and txt2man, as their format is easier for
humans to write.  It would also make the manual page more useful for
Windows users.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by sr99622** [comment]
I put first draft of this into onvif-util.  There is a -h option to view the quick help.  Will work up a man page

**Comment by petterreinholdtsen** [comment]
[sr99622]
> I put first draft of this into onvif-util.  There is a -h option to
> view the quick help.  Will work up a man page

Very good.  Did you forget to 'git add' the onvif-util.cpp file?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by sr99622** [comment]
Yes, I did forget, thank you for the heads up.

**Comment by sr99622** [comment]
A few tweaks were needed to get the code running on linux
