### ISSUE TITLE
Teach Qt application to show camera output?

### ISSUE THREAD

**Issue by petterreinholdtsen** [sr99622/libonvif#25]
It would be useful for debugging a camera connection to be able to see the camera view in one of the Qt application tabs.

**Comment by sr99622** [comment]
I do have an application that has onvif integrated into a viewer using Qt,
however it is Windows only right now.  It's been on the to-do list to make
it compatible with Linux.  If you have access to a windows machine to look
at it.

Installation link:playqt download | SourceForge.net
<https://sourceforge.net/projects/playqt/>

Source Code: sr99622/playqt: GUI Version of ffplay (github.com)
<https://github.com/sr99622/playqt>

**Comment by petterreinholdtsen** [comment]
[sr99622]
> I do have an application that has onvif integrated into a viewer using
> Qt, however it is Windows only right now.  It's been on the to-do list
> to make it compatible with Linux.  If you have access to a windows
> machine to look at it.

Aha, very good to know you too are interested in such feature.  I do not
have access to Windows.  The onvifviewer program mentioned earlier do
run on Linux.  Perhaps there is something to learn from it?  Sadly it is
not using Qt, so that part would not be transferable.

Perhaps just calling VLC with the rtmp URL would be a nice way to handle
this?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by sr99622** [comment]
That works.  I think ffplay will also work

**Comment by sr99622** [comment]
As a note, I just learned that vlc no longer supports rtsp on debian.  This is very disappointing, apparently due to some licensing issue with live555.  The gui interface will launch ffplay as a camera viewer by default.

**Comment by petterreinholdtsen** [comment]
[sr99622]
> As a note, I just learned that vlc no longer supports rtsp on debian.
> This is very disappointing, apparently due to some licensing issue
> with live555.  The gui interface will launch ffplay as a camera viewer
> by default.

Aha.  Seem to have happened in version 3.0.12-2 due to
<URL: https://bugs.debian.org/981439 >.
<URL: https://tracker.debian.org/pkg/liblivemedia > was removed and
<URL: https://tracker.debian.org/pkg/vlc > had to drop the dependency.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
Note, I suspect it is possible to embed ffmpeg into a Qt Widget.  No idea how to do it, thought.

**Comment by sr99622** [comment]
I was making some good progress with this concept on windows, but was not
able to replicate the performance on linux.  I rolled back the changes, and
would like to make one more attempt at this approach before giving up.

**Comment by sr99622** [comment]
It doesn't look like I will be able to get this running on Linux, so I
guess we will need to proceed with the current version.

**Comment by petterreinholdtsen** [comment]
[sr99622]
> It doesn't look like I will be able to get this running on Linux, so I
> guess we will need to proceed with the current version.

Was worth a try. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by sr99622** [comment]
I have finally been able to get this working.  The QtAV package works very well, and has an installation package on debian, which is libqtav-dev.  The modifications require some adjustment to CMakeLists.txt, so I don't want to change anything until you have a chance to respond.  If we are going ahead with this change, I can add some other items, such as the man page for onvif-camadmin.

**Comment by petterreinholdtsen** [comment]
[sr99622]
> I have finally been able to get this working.  The QtAV package works
> very well, and has an installation package on debian, which is
> libqtav-dev.  The modifications require some adjustment to
> CMakeLists.txt, so I don't want to change anything until you have a
> chance to respond.  If we are going ahead with this change, I can add
> some other items, such as the man page for onvif-camadmin.

Not quite sure what kind of response from me will have most positive
effect.  It sound great that you got it working, and I can test the code
in a few days if you make it available in a branch.

-- 
Happy hacking
Petter Reinholdtsen
