### ISSUE TITLE
A few fixes and extensions

### ISSUE THREAD

**Issue by BrianDScott** [sr99622/libonvif#3]
Hi,
I was having a play with some onvif video cameras using your code. Thank you.

I have attached a diff file containing some code extensions and bug fixes that you might be interested in. I have also included some rebased diffs from two forks of your code on github because they seemed interesting. One does a basic dump of returned data from the camera and the other allows access to multiple profiles.

My code adds some extra fields that I was interested in as well as a couple of extra calls (including get/set NTP).

I've also done some reworking of your time logic to better reflect UTC time vs. localtime and produced a utility to do time sync to cameras.

Do what you will with these updates. I no longer have ready access to the cameras to continue tinkering. I'd be happy to discuss my changes but can no longer test very much.

Cheers,

[libonvif-master+brian+fiz1962+kyeongy.diff.txt](https://github.com/sr99622/libonvif/files/9439123/libonvif-master%2Bbrian%2Bfiz1962%2Bkyeongy.diff.txt)

**Comment by raghunihal** [comment]
please share the code

**Comment by sr99622** [comment]
You can click on the link at the bottom of the post to get the diff

**Comment by petterreinholdtsen** [comment]
I converted the diff into a branch and pull request (#6).  The code build, but I have not yet tested it.  Look like several useful pieces, but I suspect the patch should be split into separate parts to evaluate individually. The code indentation is all over the place, but it is unclear what the intended indentation for the project is, so I am unsure how to fix it.
