### ISSUE TITLE
Give GUI tool more descriptive name?

### ISSUE THREAD

**Issue by petterreinholdtsen** [sr99622/libonvif#30]
At the moment the GUI tool is named 'onvif', which is identical to the specification name, and close to impossible to find when searching for the name on the Internet.  What about changing the GUI name to something more descriptive?

Looking at https://alternativeto.net/software/onvif-device-manager/, I notice alternatives being named ONVIF Device Manager, ONVIF Device Tool and ONVIFviewer, so those names are not good alternatives.

What about onvif-camcontrol or something like that?  I notice ONVIF have been extended to non-camera devices, so it might not be the most future proof name, but at least it matches its current behaviour.  I also note that https://www.security.honeywell.com/product-repository/camcontrol-pro have something called CamControl Pro which can control ONVIF cameras.  Perhaps 'onvif-camadmin' or 'onvif-camsetup' are better?  My search for those names did not find any matches.

**Comment by sr99622** [comment]
onvif-camadmin sounds good to me, I can update the README and CMakeLists.txt
