### ISSUE TITLE
onvif.c 

### ISSUE THREAD

**Issue by chccc1994** [sr99622/libonvif#4]
https://github.com/sr99622/libonvif/blob/30c62c4ad1d37a910f2697fcdf92400fbb2f5dd4/src/onvif.c#L1799 

1、 If the local area network contains non onvif devices, []()  Tips `Error getting camera uri ter:NotAuthorized` error. 
2、 How to filter non onvif devices？

![image](https://user-images.githubusercontent.com/68001817/188098272-2fcefa17-45c5-44a4-b4f8-a10e4d87321e.png)

**Comment by sr99622** [comment]
This is an interesting situation.  The onvif protocol has a UDP broadcast on port 3702.  Devices that respond to the broadcast are identified in a loop that starts on line 1911 in [libonvif/src/ovif.c](https://github.com/sr99622/libonvif/blob/30c62c4ad1d37a910f2697fcdf92400fbb2f5dd4/src/onvif.c#L1911).  The device response is used to populate the OnvifSession data structure buf field.  The discovery program [libonvif/example/discovery.c](https://github.com/sr99622/libonvif/blob/30c62c4ad1d37a910f2697fcdf92400fbb2f5dd4/example/discover.c#L15) then uses a loop to iterate through the OnvifSession buf to initialize an OnvifData structure for each of the devices that responded to the broadcast.

If you look at the contents of onvif_session->buf[i] in discovery.c, where i is the index of the responding device, you should be able to identify characteristics of non-onvif devices and filter accordingly.
