### ISSUE TITLE
onvif-gui: error while loading shared libraries: libonvif.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by tomcass240** [sr99622/libonvif#47]
Following the instructions exactly as described in readme. Everything went smoothly till I tried to run the gui and it says a library is missing.

Debian:~/git/libonvif/build$ sudo make install
[  8%] Built target onvif
[ 10%] Automatic MOC for target onvif-gui
[ 10%] Built target onvif-gui_autogen
[ 86%] Built target onvif-gui
[ 91%] Built target onvif-util
[100%] Built target onvif_static
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/bin/onvif-gui
-- Set runtime path of "/usr/local/bin/onvif-gui" to ""
-- Installing: /usr/local/bin/onvif-util
-- Set runtime path of "/usr/local/bin/onvif-util" to ""
-- Installing: /usr/local/lib/libonvif.so.1
-- Set runtime path of "/usr/local/lib/libonvif.so.1" to ""
-- Installing: /usr/local/lib/libonvif.so
-- Installing: /usr/local/lib/libonvif_static.a
-- Installing: /usr/local/include/x86_64-linux-gnu/onvif.h
-- Installing: /usr/local/share/man/man1/onvif-util.1
-- Installing: /usr/local/share/man/man1/onvif-gui.1
debian:~/git/libonvif/build$ onvif-gui
onvif-gui: error while loading shared libraries: libonvif.so.1: cannot open shared object file: No such file or directory
debian:~/git/libonvif/build$

**Comment by tomcass240** [comment]
sorry i hope you can read it no idea why it's strikethrough.

**Comment by sr99622** [comment]
It looks like libonvif.so.1 was installed to /usr/local/lib.  For the current session you can use the command 
```bin
export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib
```
or to make the change permanent you can add /usr/local/lib to /etc/ld.so.conf (or something it includes) and run ldconfig as root.

If you're still having problems, running ldd [executable name] will show you the libraries it's trying to find, and which ones can't be found.  The link below shows some detailed answers to a very similar issue.

https://unix.stackexchange.com/questions/67781/use-shared-libraries-in-usr-local-lib

I suppose I should add these notes to the README

**Comment by tomcass240** [comment]
yeah that fixed it. weird that the environment variable isn't just loaded at startup to use /usr/local/lib for libraries as there were quite a few libraries in there so I wonder if that's been the cause of any other problems I might have had in the past. I read I can just add export env variable to my .bashrc and that should fix it.
