### ISSUE TITLE
List of manually added cameras disappear after every relaunch

### ISSUE THREAD

**Issue by AntonKrychevskyy** [sr99622/libonvif#94]
Hi. I am using onvif-gui on Fedora 40. I've switched to Cached Addresses option in Settings tab and manually added two IP cameras. They worked normally. But when I close the program and starts it again the list of cameras is empty. Am I doing something wrong or it is suppose to behave like that?

Thank you.

**Comment by sr99622** [comment]
Hi Anton,

The cached addresses should re-appear if the Discovery is performed. This is not done by default, but there are two ways to perform discovery. You can click the discover button on the camera panel to perform a one-time discover, or you can set the Auto Discovery check box on the Settings Panel to automatically perform discovery each time upon start up.

Note that if discovery is not performed and the program is closed without any cameras shown in the list, the cache will be cleared.

Thank you so much for reaching out, I hope this clears up the issue. If you need further help, please let me know.

Best Regards,

Stephen

**Comment by AntonKrychevskyy** [comment]
Oh, ok. Great. Thanks
