### ISSUE TITLE
Version 1.2.9 stopped working on Ubuntu 22.04.4

### ISSUE THREAD

**Issue by leechpool-github** [sr99622/libonvif#97]
Just putting this here in case it helps someone else... I had installed version 1.2.9 a long time ago. I love the program (thanks again Stephen Rhodes :) ). My wife and I use it every day, several times a day to view and pan/zoom etc our Hikvision cameras. Version 1.2.9 worked great until recently, but on my PC running Ubuntu 22.04.4, whenever I tried to run it in the last few days, the window would open as usual but then nothing would happen. I was left looking at a blank window. Running from command line showed no error.
So given that there was a much never version available, I tried reinstalling in a second virtual environment:

virtualenv myenv2
source myenv2/bin/activate
pip install onvif-gui
onvif-gui

Now version 2.2.8 works brilliantly and I look forward to enjoying the improvements (like cached IP addresses).

Interestingly, my wife's laptop also running Ubuntu 22.04.4 still seems to run version 1.2.9 without issue, so it could be that I had done something stupid that stopped it working, or possibly my wife's PC has just not installed an update which somehow breaks 1.2.9. In any event, 2.2.8 seems to work great with Ubuntu 22.04.4.

:)

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by sr99622** [comment]
Thank you so much for your kind words. The older version is not being
supported any more. It has dependency on ffmpeg, which recently underwent
some changes that would require some significant reworking of the older
code. The more recent updates for Ubuntu will install the new ffmpeg which
will break the older version of the program unfortunately.

The current version should be working in either environment.

More improvements are on the way, so keep an eye open for those :)
